SRCS-mchck=	builtins.c system.c gpio.c pin.c adc.c spi.c sg.c timeout.c
SRCS-mchck+=	flash.c onboard-led.c stdio.c printf.c ftm.c

SRCS.force-mchck+=	startup_${TARGET_FAMILY_SHORT}.c

ifdef LOADER
SRCS.force-mchck+=	flashconfig_${TARGET_FAMILY_SHORT}.c
endif

SRCS.libs+=	mchck
